import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const dialog = readFileSync(new URL('./ServiceCreateDialog.vue', import.meta.url), 'utf8')
const knowledgeBasePicker = readFileSync(new URL('./ServiceKnowledgeBasePickerDialog.vue', import.meta.url), 'utf8')
const hub = readFileSync(new URL('./ServiceHub.vue', import.meta.url), 'utf8')
const hubState = readFileSync(new URL('./serviceHubState.ts', import.meta.url), 'utf8')
const menu = readFileSync(new URL('../../components/ServiceHubMenu.vue', import.meta.url), 'utf8')
const router = readFileSync(new URL('../../router/index.ts', import.meta.url), 'utf8')
const mobileRouter = readFileSync(new URL('../../mobile-main.ts', import.meta.url), 'utf8')
const overview = readFileSync(new URL('./ServiceOverviewView.vue', import.meta.url), 'utf8')
const subjects = readFileSync(new URL('./ServiceSubjectsView.vue', import.meta.url), 'utf8')
const settings = readFileSync(new URL('./ServiceSettingsView.vue', import.meta.url), 'utf8')

test('service creation has a routed page mode and loads account-visible knowledge bases', () => {
  assert.match(dialog, /:disabled="displayMode === 'page'"/)
  assert.match(dialog, /class="service-create-dialog-overlay"/)
  assert.match(hub, /view === 'create'/)
  assert.match(hub, /display-mode="page"/)
  assert.match(hub, /if \(isCreateRoute\) view\.value = 'create'\s+await loadServiceHub\(\)/)
  assert.match(dialog, /fetchMyKnowledgeBases\(true\)/)
  assert.match(dialog, /validAccountKnowledgeBases/)
  assert.match(dialog, /ServiceKnowledgeBasePickerDialog/)
  assert.match(dialog, /v-model:visible="knowledgeBasePickerVisible"/)
  assert.match(dialog, /知识库/)
  assert.match(hub, /instruction: payload\.instruction/)
  assert.doesNotMatch(hub, /space_type: payload\.spaceType/)
  assert.match(router, /path: "service\/new"/)
  assert.match(router, /name: "serviceCreate"/)
})

test('knowledge-base add action opens a searchable permission-scoped multi-select dialog', () => {
  assert.doesNotMatch(dialog, /knowledgeBasePickerOpen/)
  assert.match(dialog, /@click="knowledgeBasePickerVisible = true"/)
  assert.match(knowledgeBasePicker, /当前账号有权访问的全部知识库/)
  assert.match(knowledgeBasePicker, /filteredKnowledgeBases/)
  assert.match(knowledgeBasePicker, /draftSelectedIds/)
  assert.match(knowledgeBasePicker, /accessSourceLabel/)
  assert.match(knowledgeBasePicker, /permissionLabel/)
  assert.match(knowledgeBasePicker, /case 'created'/)
  assert.match(knowledgeBasePicker, /case 'shared_space'/)
  assert.match(knowledgeBasePicker, /case 'subscription'/)
  assert.match(knowledgeBasePicker, /confirm: \[ids: string\[\]\]/)
})

test('service creation stays business-facing and does not expose skills or machine keys', () => {
  assert.doesNotMatch(dialog, /技能/)
  assert.doesNotMatch(hub, /serviceSkills/)
  assert.doesNotMatch(dialog, /space_key|expert_ref|subject_ref/)
  assert.doesNotMatch(dialog, /主要围绕谁工作/)
  assert.doesNotMatch(dialog, /serviceTypeOptions|spaceType/)
  assert.match(dialog, /系统会根据工作指令生成重点记录/)
  assert.match(dialog, /请描述这个服务要完成的工作/)
  assert.match(dialog, /!form\.name\.trim\(\) \|\| !form\.instruction\.trim\(\)/)
})

test('service experts come from published system experts and use a searchable picker', () => {
  assert.match(dialog, /ServiceExpertPickerDialog/)
  assert.match(dialog, /serviceExpertsLoading/)
  assert.match(dialog, /serviceExpertsError/)
  assert.match(hubState, /listPublishedExperts/)
  assert.match(hubState, /loadServiceExperts/)
})

test('service creation uses the built-in assistant when experts are optional and empty', () => {
  assert.match(hub, /payload\.expertIds\.length/)
  assert.match(hub, /expert_ref: BUILTIN_SMART_REASONING_ID/)
  assert.match(hub, /expert_name: '服务助理'/)
  assert.match(hub, /activate: true/)
  assert.match(hub, /const session = await ensureServiceSession\(serviceId\)/)
})

test('templates live under my services and populate the creation dialog', () => {
  assert.match(hub, /我的服务/)
  assert.match(hub, /从模板创建/)
  assert.match(hub, /v-for="group in filteredTemplateGroups"/)
  assert.match(hub, /@click="openCreate\(template\)"/)
  assert.match(hub, /:source="createSource"/)
  assert.match(dialog, /template\?\.description/)
  assert.match(dialog, /template\?\.instruction/)
  assert.doesNotMatch(dialog, /推荐配置/)
  assert.doesNotMatch(dialog, /当前工作画像/)
  assert.doesNotMatch(dialog, /切换模板/)
  assert.match(dialog, /已带入模板/)
  assert.match(dialog, /创建后仍可调整/)
  assert.match(dialog, /创建服务/)
})

test('planned service flow creates and activates without a blueprint confirmation step', () => {
  assert.match(hub, /applyServiceTemplate/)
  assert.match(hub, /activate: true/)
  assert.match(hub, /if \(!selectedTemplate\?\.autoApply\)/)
  assert.doesNotMatch(hub, /previewServiceBlueprint/)
  assert.doesNotMatch(hub, /confirmServiceBlueprint/)
  assert.doesNotMatch(hub, /确认服务空间蓝图/)
  assert.match(hub, /await openCreatedService\(serviceId\)/)
})

test('service workspace keeps only artifacts and reminders as primary tools', () => {
  assert.match(hub, /const headTools = computed/)
  assert.match(hub, /key: 'artifacts'/)
  assert.match(hub, /key: 'reminders'/)
  assert.doesNotMatch(hub, /key: 'context'.*headTools/s)
  assert.match(hub, /修改服务名称/)
  assert.match(hub, /修改服务描述/)
  assert.match(hub, /分享服务/)
})

test('service routes support shareable service and session paths', () => {
  assert.match(router, /path: "service\/:serviceId\/sessions\/:sessionId"/)
  assert.match(router, /name: "serviceSession"/)
  assert.match(router, /path: "service\/:serviceId"/)
  assert.match(router, /name: "serviceWorkspace"/)
  assert.match(hub, /route\.params\.serviceId/)
  assert.match(hub, /route\.params\.sessionId/)
})

test('service sidebar creates sessions inline and limits the initial session list', () => {
  assert.match(menu, /const SESSION_LIMIT = 8/)
  assert.match(menu, /class="service-hub-session-count-action"/)
  assert.match(menu, /startServiceSession\(service\.id\)/)
  assert.match(menu, /还有 \{\{ hiddenSessionCount\(service\.id\) \}\} 个/)
  assert.match(menu, /beginSessionRename/)
  assert.match(menu, /toggleSessionPinned/)
  assert.match(menu, /confirmRemoveSession/)
  assert.doesNotMatch(menu, /service-hub-service-icon/)
})

test('service overview, subjects, and settings use shareable full-page routes', () => {
  assert.match(router, /path: "service\/:serviceId\/overview"/)
  assert.match(router, /path: "service\/:serviceId\/subjects"/)
  assert.match(router, /path: "service\/:serviceId\/settings\/:section\?"/)
  assert.match(mobileRouter, /path: '\/mobile\/service\/:serviceId\/overview'/)
  assert.match(mobileRouter, /path: '\/mobile\/service\/:serviceId\/subjects'/)
  assert.match(mobileRouter, /path: '\/mobile\/service\/:serviceId\/settings\/:section\?'/)
  assert.match(overview, /getServiceProfile/)
  assert.match(overview, /getServiceSummary/)
  assert.match(overview, /refreshServiceSummary/)
  assert.match(hub, /openServicePage\('overview'\)/)
  assert.match(hub, /openServicePage\('subjects'\)/)
  assert.match(hub, /openServicePage\('settings\/basic'\)/)
})

test('service settings and subjects stay business-facing without machine identifiers', () => {
  assert.match(settings, /基本信息/)
  assert.match(settings, /重点记录/)
  assert.match(settings, /资料/)
  assert.match(settings, /成员/)
  assert.match(settings, /listServiceContextSources/)
  assert.match(settings, /listServiceMembers/)
  assert.match(settings, /const loading = ref\(true\)/)
  assert.match(subjects, /createServiceSubject\(serviceId\.value, \{ display_name: displayName \}\)/)
  assert.doesNotMatch(subjects, /subject_key|subject_type|唯一标识/)
  assert.doesNotMatch(settings, /字段 key|状态 key|用户 ID/)
})

test('service workspace exposes service-scoped reminders and status actions', () => {
  assert.match(hub, /panel === 'reminders'/)
  assert.match(hub, /listServiceReminders/)
  assert.match(hub, /createServiceReminder/)
  assert.match(hub, /updateServiceReminder/)
  assert.match(hub, /deleteServiceReminder/)
  assert.match(hub, /nextReminderStatuses/)
  assert.match(hub, /服务待办/)
  assert.match(hub, /待办已创建/)
})

test('market research template covers the full research-to-review workflow', () => {
  assert.match(hubState, /市场调研与竞品分析协同助手/)
  assert.match(hubState, /阶段一：调研课题定义/)
  assert.match(hubState, /阶段七：持续跟踪/)
  assert.match(hubState, /事实、分析和建议/)
  assert.match(hubState, /调研结论评审/)
  assert.match(hubState, /调研主体/)
})

test('early childhood membership template covers member lifecycle service', () => {
  assert.match(hubState, /早教机构会员服务/)
  assert.match(hubState, /会员家庭/)
  assert.match(hubState, /会员档案/)
  assert.match(hubState, /课程预约与调整/)
  assert.match(hubState, /权益与使用/)
  assert.match(hubState, /投诉与负面反馈/)
  assert.match(hubState, /儿童健康或安全相关情形/)
  assert.match(hubState, /续费风险/)
})
