blank_issues_enabled: false
contact_links:
  - name: 睿乐大脑 Documentation
    url: https://github.com/Tencent/WeKnora/blob/main/docs/QA.md
    about: Check 睿乐大脑 FAQ
  - name: Discussions
    url: https://github.com/Tencent/WeKnora/discussions
    about: Ask questions or share ideas in Discussions
