import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const source = readFileSync(new URL('./OrganizeDocumentEditor.vue', import.meta.url), 'utf8')
const serviceExtractionSource = readFileSync(new URL('../service/serviceMemoryExtraction.ts', import.meta.url), 'utf8')

test('document editor opens slash menu after leading whitespace', () => {
  assert.match(source, /@keydown\.capture="handleEditorKeydown"/)
  assert.ok(source.includes("event.key !== '/'"))
  assert.match(source, /\/\^\\s\+\$\/\.test\(textBeforeCursor\)/)
  assert.ok(source.includes("deleteRange({ from: $from.start(), to: $from.pos }).insertContent('/')"))
})

test('memory note editor exposes note controls without the format toolbar', () => {
  assert.ok(source.includes('isNoteMemory'))
  assert.ok(source.includes('memory-note-tabs'))
  assert.ok(source.includes("noteActiveTab === 'service'"))
  assert.ok(source.includes('buildServiceTaskFromMemory'))
  assert.ok(source.includes('formatMemoryDateLabel'))
  assert.ok(source.includes('noteServiceTask'))
  assert.ok(source.includes('memory-note-service-card'))
  assert.ok(source.includes('editor-service-action'))
  assert.ok(source.includes('extractServiceMemory'))
  assert.ok(source.includes('extractCurrentMemoryToService'))
  assert.ok(source.includes('agent-green.svg'))
  assert.ok(source.includes('提取服务'))
  assert.ok(source.includes('有利于销售的信息'))
  assert.ok(source.includes('来源关联'))
  assert.ok(source.includes('暂无服务资料'))
  assert.ok(source.includes('添加标签'))
  assert.ok(source.includes('智能标签'))
  assert.ok(source.includes('noteTagIcon'))
  assert.ok(source.includes('memory-note-tag-leading-icon'))
  assert.ok(source.includes('memory-note-tag-action'))
  assert.ok(source.includes('memory-note-tag-smart-button'))
  assert.ok(source.includes('font-size: 13px;'))
  assert.ok(source.includes('background: #fbfcff;'))
  assert.ok(source.includes('createMemorySprout'))
  assert.ok(source.includes('listOrganizeSproutReports'))
  assert.ok(source.includes('noteSproutCard'))
  assert.ok(source.includes('memory_refs'))
  assert.ok(source.includes('memory_id: memoryID'))
  assert.ok(source.includes('referenceLabels'))
  assert.ok(source.includes('@创建了'))
  assert.ok(source.includes('editor-sprout-action'))
  assert.ok(source.includes('editor-sprout-action-icon'))
  assert.ok(source.includes('noteSproutHeaderState'))
  assert.ok(source.includes('handleMemorySproutHeaderAction'))
  assert.ok(source.includes('sprout-report-card'))
  assert.ok(source.includes('sprout-report-ribbon'))
  assert.ok(source.includes('sprout-preview-drawer'))
  assert.ok(source.includes('activeNoteSproutPreview'))
  assert.ok(source.includes('sproutPreviewVisible.value = true'))
  assert.ok(source.includes('closeNoteSproutPreview'))
  assert.ok(source.includes('openNoteSproutEditor'))
  assert.ok(source.includes('sproutReportContentForEditor(contentSource)'))
  assert.ok(source.includes('memory-note-source-card'))
  assert.ok(source.includes('sourceFileCardVisible'))
  assert.ok(source.includes('sourcePreviewVisible'))
  assert.ok(source.includes('openSourceFilePreview'))
  assert.ok(source.includes('DocumentPreview'))
  assert.ok(source.includes("new URLSearchParams({ file_path: source })"))
  assert.ok(source.includes(':version="editorVersion"'))
  assert.ok(!source.includes('memory-note-toolbar'))
  assert.ok(!source.includes('追加笔记'))
  assert.ok(!source.includes('appendNoteText'))
  assert.ok(!source.includes('appendMemoryText'))
  assert.ok(!source.includes('加入服务'))
  assert.ok(!source.includes('memory-note-meta'))
  assert.ok(!source.includes('memory-note-tag-empty'))
  assert.ok(!source.includes('还没有标签'))
  assert.ok(!source.includes('memory-note-sprout-placeholder'))
  assert.ok(!source.includes('暂无发芽结果'))
  assert.ok(!source.includes('等待生成后的发芽结果。'))
  assert.ok(!source.includes('<h3>发芽</h3>'))
  assert.ok(!source.includes('memory-note-sprout-create-button'))
  assert.ok(!source.includes('memory-note-sprout-button-icon'))
  assert.ok(!source.includes('把这条笔记整理成可继续复盘的发芽结果。'))
  assert.ok(!source.includes('还没有发芽结果，点击按钮开始生成。'))
  assert.ok(!source.includes('<span>@记忆</span>'))
})

test('memory service tab uses shared weak extraction rules', () => {
  assert.ok(serviceExtractionSource.includes('export const isServiceMemory'))
  assert.ok(serviceExtractionSource.includes('Boolean(extractCustomerName(memory)) && hasServiceBusinessSignal(memory, text)'))
  assert.ok(serviceExtractionSource.includes('export const buildServiceTaskFromMemory'))
  assert.ok(serviceExtractionSource.includes('sourceMemoryIds'))
  assert.ok(serviceExtractionSource.includes('salesHighlights'))
  assert.ok(serviceExtractionSource.includes('出现售前接触信号'))
})

test('memory note editor lets the page own mouse wheel scrolling', () => {
  assert.ok(source.includes('.document-editor-shell--memory-note :deep(.tiptap-pro-editor.word-mode)'))
  assert.ok(source.includes('.document-editor-shell--memory-note :deep(.word-document-container)'))
  assert.ok(source.includes('height: auto;'))
  assert.ok(source.includes('overflow: visible;'))
  assert.ok(source.includes('overscroll-behavior-y: auto;'))
})
