import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const source = readFileSync(new URL('./OrganizeLessonDetail.vue', import.meta.url), 'utf8')

test('course lesson media uses an OSS direct URL without a server blob fallback', () => {
  assert.ok(!source.includes("import { getDown } from '@/utils/request'"))
  assert.ok(source.includes('getOrganizeCourseLessonMediaURL(courseId.value, lessonId.value, {'))
  assert.ok(source.includes("const directUrl = response.success ? response.data?.url || '' : ''"))
  assert.ok(source.includes('isDirectMediaUrl(directUrl)'))
  assert.ok(source.includes('mediaPlayerUrl.value = directUrl'))
  assert.ok(!source.includes('getDown('))
  assert.ok(!source.includes('URL.createObjectURL'))
  assert.ok(!source.includes('URL.revokeObjectURL'))
  assert.ok(source.includes('const controller = new AbortController()'))
  assert.ok(source.includes('signal: controller.signal'))
  assert.ok(source.includes('courseAbortController?.abort()'))
  assert.ok(source.includes('mediaAbortController?.abort()'))
  assert.ok(source.includes('element.removeAttribute(\'src\')'))
  assert.ok(source.includes('element.load()'))
  assert.ok(source.includes('timeout: 0'))
  assert.ok(source.includes('onBeforeUnmount(() => {'))
})

test('course lesson media does not bind the protected API URL directly to the player', () => {
  assert.ok(source.includes(':src="mediaPlayerUrl"'))
  assert.ok(!source.includes(':src="mediaUrl"'))
  assert.ok(source.includes('@error="handleMediaPlaybackError"'))
  assert.ok(source.includes('mediaDirectRetryAttempted'))
  assert.ok(source.includes('浏览器无法读取对象存储媒体文件'))
  assert.ok(!source.includes('mediaEndpointUrl'))
  assert.ok(source.includes('aspect-ratio: 16 / 9'))
  assert.ok(source.includes('object-fit: contain'))
  assert.ok(source.includes('v-if="lecturerLabel"'))
  assert.ok(source.includes('<span>讲师：</span>'))
  assert.ok(source.includes('<t-icon name="user" />'))
  assert.ok(source.includes('course.value?.teacher_name'))
  assert.ok(source.includes('course.value?.teacher_title'))
  assert.ok(!source.includes('本讲来自 admin 上传文件夹中的：'))
  assert.ok(source.includes('@click="backToDiscover"'))
  assert.ok(source.includes('.organize-back-button'))
  assert.ok(source.includes('border: none'))
  assert.ok(!source.includes('@click="backToCourse"'))
  assert.ok(!source.includes('organize-lesson-crumb'))
  assert.ok(!source.includes('getOrganizeCourseLessonContent'))
  assert.ok(!source.includes('loadLessonBody'))
  assert.ok(!source.includes('本讲暂无正文'))
  assert.ok(!source.includes('MessagePlugin'))
})
